In [22]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [23]:
import numpy as np
data=np.random.randint(0,10,(3,3))
data

array([[1, 6, 5],
       [2, 2, 2],
       [7, 8, 4]], dtype=int32)

In [5]:
np.random.randn(3,3)

array([[ 1.34919034, -1.43885088, -1.41634229],
       [ 0.75965868, -0.27749484,  1.20525733],
       [ 1.14284437,  1.45302142,  0.57212537]])

In [30]:
np.random.randn(30,30).std()

np.float64(0.9944024948323078)

In [31]:
np.random.randn(30,30).mean()

np.float64(-0.01725736430641939)

In [3]:
import numpy as np

In [ ]:


retail_data = np.array([[ 1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]])

print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [4]:
#1. What is the **total revenue** generated across all stores?
retail_data[:,4].sum()

np.int64(142)

In [5]:
#2. Which store recorded the **highest sales**?
retail_data[:,1].argmax()+1

np.int64(9)

In [6]:
#3. Which store recorded the **lowest sales**?
retail_data[:,1].argmin()+1

np.int64(1)

In [7]:
#4. What is the **average daily sales** per store?
retail_data[:,1].sum()/10

np.float64(33500.0)

In [8]:
#5. How many stores achieved sales **above ₹35,000**?
data = retail_data[:,1]
data[data>35000]

array([41000, 39000, 45000])

In [9]:
6. Which store had the **highest customer footfall**?
retail_data[:,2].argmin()+1

np.int64(1)

In [13]:
#7. What is the **average number of customers** per store?
retail_data[:,2].sum()/10

np.float64(425.0)

In [12]:
#8. How many stores have **more than 450 customers**?
data = retail_data[:,2]
data[data>450]

array([500, 480, 550])

In [11]:
#9. Which store has the **lowest customer count**?
retail_data[:,2].argmin()+1

np.int64(1)

In [10]:
#10. Is there any store where **high sales do not correspond to high customers**?
sal = retail_data[:,1].mean()
cus = retail_data[:,2].mean()
mis = retail_data[(retail_data[:,1]>sal)&(retail_data[:,2]<cus)]
mis


array([[    5, 35000,   420,  1400,    12]])

In [14]:
#11. What is the **total inventory** across all stores?
retail_data[:,3].sum()

np.int64(14300)

In [15]:
#12. Which store has the **highest inventory stock**?
retail_data[:,3].argmax()+1

np.int64(9)

In [16]:
#13. How many stores have **inventory less than 1300 units**?
data = retail_data[:,3]
data[data<1300]

array([1200, 1100, 1250])

In [17]:
#14. Which store has the **highest return rate** (returns ÷ inventory)?
data = retail_data[:,4]/retail_data[:,3].argmax()+1
data

array([2.25 , 2.875, 2.   , 3.5  , 2.5  , 2.125, 3.25 , 2.75 , 4.125,
       2.375])

In [18]:
#15. Which stores have **returns greater than 15 units**?
data = retail_data[retail_data[:,4]>15]
data

array([[    4, 41000,   500,  1600,    20],
       [    7, 39000,   480,  1700,    18],
       [    9, 45000,   550,  1800,    25]])

In [ ]:
#16. Is there a **positive correlation** between sales and customers?

In [19]:
#17. Which store has **high customer visits but low sales**?
cus = retail_data[:,2].mean()
sal = retail_data[:,1].mean()
data = retail_data[(retail_data[:,2]>cus)&(retail_data[:,1]<sal)]
data


array([[    2, 32000,   450,  1500,    15]])

In [20]:
18. Which store has **low customers but high sales**?
cus = retail_data[:,2].mean()
sal = retail_data[:,1].mean()
data = retail_data[(retail_data[:,2]<cus)&(retail_data[:,1]>sal)]
data

array([[    5, 35000,   420,  1400,    12]])

In [21]:
#19. How many stores have **sales per customer above ₹90**?
customer = retail_data[:,1] / retail_data[:,2]
new = np.sum(customer>90)
new

np.int64(0)

In [ ]:
#20. Which stores could **benifit from customer acquisition campaigns ** (low customers,high inventory)

In [22]:
#21. If profit margin is **20% of sales**, what is the **profit per store**?
data = 0.20 * retail_data[:,1]
data


array([5000., 6400., 5600., 8200., 7000., 5400., 7800., 6000., 9000.,
       6600.])

In [23]:
#22. Which store has the **highest profit**?
(retail_data[:,1]*0.20).argmax()+1

np.int64(9)

In [24]:
#23. Which store has the **lowest profit**?
(retail_data[:,1]*0.20).argmin()+1

np.int64(1)

In [25]:
#24. If sales increase by **10% next month**, what are the **new sales figures**?
(retail_data[:,1]*0.10) 

array([2500., 3200., 2800., 4100., 3500., 2700., 3900., 3000., 4500.,
       3300.])

In [26]:
#25. How will **total profit** change with the 10% sales increase?
(retail_data[:,1]*0.10) + retail_data[:,1]

array([27500., 35200., 30800., 45100., 38500., 29700., 42900., 33000.,
       49500., 36300.])

In [27]:
#26. Which stores need **inventory restocking** based on sales and current stock?
sal = retail_data[:,1].mean()
ret = retail_data[:,4].mean()
data = retail_data[(retail_data[:,1]>sal) > (retail_data[:,4]>ret)]
data

array([[    5, 35000,   420,  1400,    12]])

In [28]:
#27. Which stores show **high returns percentage** and might require **quality checks**?
aver = retail_data[:,4].mean()
res = retail_data[(retail_data[:,4] >aver)]
res

array([[    2, 32000,   450,  1500,    15],
       [    4, 41000,   500,  1600,    20],
       [    7, 39000,   480,  1700,    18],
       [    9, 45000,   550,  1800,    25]])

In [31]:
#30. Which stores can be considered for **expansion** based on strong sales and customer metrics?

sal = retail_data[:,1].mean()
cus = retail_data[:,2].mean()
data = retail_data[(retail_data[:,1]>sal)&(retail_data[:,2]>cus)]
data


array([[    4, 41000,   500,  1600,    20],
       [    7, 39000,   480,  1700,    18],
       [    9, 45000,   550,  1800,    25]])